menu/urls.py
from django.urls import path
from .views import (index,
                    DishListView,
                    DishDetailView,
                    DishCreateView,
                    DishUpdateView,
                    DishDeleteView,
                    DishTypeListView,
                    DishTypeDetailView,
                    DishTypeCreateView,
                    DishTypeUpdateView,
                    DishTypeDeleteView,
                    CookListView,
                    CookDetailView,
                    CookCreateView,
                    CookUpdateView,
                    CookDeleteView,
                    toggle_assign_to_dish)

urlpatterns = [
    path("", index, name="index"),
    path("menu/", DishListView.as_view(), name="dish-list"),
    path("menu/<int:pk>/",
         DishDetailView.as_view(),
         name="dish-detail"),
    path("menu/create/",
         DishCreateView.as_view(),
         name="dish-create"),
    path("menu/<int:pk>/update/",
         DishUpdateView.as_view(),
         name="dish-update"),
    path("menu/<int:pk>/delete/",
         DishDeleteView.as_view(),
         name="dish-delete"),

    path("menu/types/", DishTypeListView.as_view(), name="dish_type_list"),
    path("menu/types/<int:pk>/",
         DishTypeDetailView.as_view(),
         name="dish_type_detail"),
    path("menu/types/create/",
         DishTypeCreateView.as_view(),
         name="dish-type-create"),
    path("menu/types/update/<int:pk>/",
         DishTypeUpdateView.as_view(),
         name="dish-type-update"),
    path("menu/types/delete/<int:pk>/",
         DishTypeDeleteView.as_view(),
         name="dish-type-delete"),

    path("menu/cooks/", CookListView.as_view(), name="cook-list"),
    path("menu/cooks/<int:pk>/",
         CookDetailView.as_view(),
         name="cook-detail"),
    path("menu/cooks/create/",
         CookCreateView.as_view(),
         name="cook-create"),
    path("menu/cooks/update/<int:pk>/",
         CookUpdateView.as_view(),
         name="cook-update"),
    path("menu/cooks/delete/<int:pk>/",
         CookDeleteView.as_view(),
         name="cook-delete"),
    path("menu/cooks/assign_to_dish/<int:pk>/",
         toggle_assign_to_dish,
         name="assign-to-dish"),
]


app_name = "menu"

restaurant/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from menu.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("menu.urls", namespace="menu")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/profile/", index),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/navigation.html
  <!-- Navbar -->
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg  blur border-radius-xl mt-4 top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid px-0">
            <a class="navbar-brand font-weight-bolder ms-sm-3" href="/" rel="tooltip"  data-placement="bottom">
              Home
            </a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
            <div class="pt-3 pb-2 py-lg-0 w-100" id="navigation">
              <ul class="navbar-nav navbar-nav-hover ms-auto">
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a class="nav-link ps-2 d-flex cursor-pointer align-items-center" id="dropdownMenuPages" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="material-icons opacity-6 me-2 text-md">dashboard</i>
                    Pages
                    <img src="{{ ASSETS_ROOT }}/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-auto ms-md-2">
                  </a>
                  <div class="dropdown-menu dropdown-menu-animation ms-n3 dropdown-md p-3 border-radius-xl mt-0 mt-lg-3" aria-labelledby="dropdownMenuPages">
                    <div class="d-none d-lg-block">
                      <a href="{% url 'menu:dish-list' %}" class="dropdown-item border-radius-md">
                        <span>Our Menu</span>
                      </a>
                      <a href="{% url 'menu:cook-list' %}" class="dropdown-item border-radius-md">
                        <span>List of Our Cookers</span>
                      </a>
                      <a href="{% url 'menu:dish_type_list' %}" class="dropdown-item border-radius-md">
                        <span>Countries of our meals</span>
                      </a>
                    </div>
                  </div>
                </li>

                {% if request.user.is_authenticated %}
                  <li class="nav-item ms-lg-auto">
                    <a class="nav-link nav-link-icon me-2"
                      href="{% url 'logout' %}">{{ user.get_username }}
                      <i class="fa fa-sign-out me-1"></i>
                      <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Sign OUT">Logout</p>
                    </a>
                  </li>
                {% endif %}
                {% if not request.user.is_authenticated %}
                  <li class="nav-item ms-lg-auto">
                    <a class="nav-link nav-link-icon me-2"
                      href="{% url 'login' %}">
                      <i class="fa fa-sign-out me-1"></i>
                      <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Login">Login</p>
                    </a>
                  </li>
                {% endif %}

              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number  %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }}/{{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number  %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/scripts.html
<!--   Core JS Files   -->
<script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>

<!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
<script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/prism.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/highlight.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
<script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
<!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
<script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
<!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
<script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>

<!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
<script src="{{ ASSETS_ROOT }}/js/material-kit.min.js?v=3.0.0" type="text/javascript"></script>