menu/urls.py
from django.urls import path
from .views import (index,
                    DishListView,
                    DishDetailView,
                    DishCreateView,
                    DishUpdateView,
                    DishDeleteView,
                    DishTypeListView,
                    DishTypeDetailView,
                    DishTypeCreateView,
                    DishTypeUpdateView,
                    DishTypeDeleteView,
                    CookListView,
                    CookDetailView,
                    CookCreateView,
                    CookUpdateView,
                    CookDeleteView,
                    toggle_assign_to_dish)

urlpatterns = [
    path("", index, name="index"),
    path("menu/", DishListView.as_view(), name="dish-list"),
    path("menu/<int:pk>/",
         DishDetailView.as_view(),
         name="dish-detail"),
    path("menu/create/",
         DishCreateView.as_view(),
         name="dish-create"),
    path("menu/<int:pk>/update/",
         DishUpdateView.as_view(),
         name="dish-update"),
    path("menu/<int:pk>/delete/",
         DishDeleteView.as_view(),
         name="dish-delete"),

    path("menu/types/", DishTypeListView.as_view(), name="dish_type_list"),
    path("menu/types/<int:pk>/",
         DishTypeDetailView.as_view(),
         name="dish_type_detail"),
    path("menu/types/create/",
         DishTypeCreateView.as_view(),
         name="dish-type-create"),
    path("menu/types/update/<int:pk>/",
         DishTypeUpdateView.as_view(),
         name="dish-type-update"),
    path("menu/types/delete/<int:pk>/",
         DishTypeDeleteView.as_view(),
         name="dish-type-delete"),

    path("menu/cooks/", CookListView.as_view(), name="cook-list"),
    path("menu/cooks/<int:pk>/",
         CookDetailView.as_view(),
         name="cook-detail"),
    path("menu/cooks/create/",
         CookCreateView.as_view(),
         name="cook-create"),
    path("menu/cooks/update/<int:pk>/",
         CookUpdateView.as_view(),
         name="cook-update"),
    path("menu/cooks/delete/<int:pk>/",
         CookDeleteView.as_view(),
         name="cook-delete"),
    path("menu/cooks/assign_to_dish/<int:pk>/",
         toggle_assign_to_dish,
         name="assign-to-dish"),
]


app_name = "menu"

restaurant/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from menu.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("menu.urls", namespace="menu")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/profile/", index),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

menu/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class DishType(models.Model):
    name = models.CharField(max_length=255)

    class Meta:

        ordering = ["name"]

    def __str__(self) -> str:
        return self.name


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(null=True, blank=True)

    class Meta:
        verbose_name_plural = "cookers"

    def __str__(self) -> str:
        return (f"{self.username}"
                f" | {self.first_name} {self.last_name}"
                f" | {self.years_of_experience}")


class Dish(models.Model):
    name = models.CharField(max_length=63)
    description = models.TextField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    dish_type = models.ForeignKey(DishType, on_delete=models.CASCADE)
    cookers = models.ManyToManyField(Cook, related_name="dishes")

    class Meta:
        verbose_name_plural = "dishes"
        ordering = ["dish_type"]

    def __str__(self) -> str:
        return f"{self.name} | {self.price}"

menu/forms.py
from __future__ import annotations
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from .models import Cook, Dish


class DishForm(forms.ModelForm):
    cookers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Dish
        fields = "__all__"


class CookSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username"})
    )


class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"})
    )


class DishTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"})
    )


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience",
            "first_name",
            "last_name",
        )

    def clean_years_of_experience(self) -> None:
        return validate_experience(
            self.cleaned_data["years_of_experience"]
        )


class CookUpdateYearsForm(forms.ModelForm):
    class Meta:
        model = Cook
        fields = ["years_of_experience"]

    def clean_years_of_experience(self) -> None:
        return validate_experience(self.cleaned_data["years_of_experience"])


def validate_experience(years_of_experience) -> str | int:
    if years_of_experience < 1:
        raise ValidationError(
            "You need to have at least one year of experience"
        )
    elif years_of_experience > 45:
        raise ValidationError("Are you sure, grandpa?")

    return years_of_experience

menu/views.py
from django.db.models import QuerySet
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from .forms import (DishForm,
                    CookSearchForm,
                    DishSearchForm,
                    CookCreationForm,
                    CookUpdateYearsForm,
                    DishTypeSearchForm)
from .models import Dish, DishType, Cook


# @login_required
def index(request):
    """View function for the home page of the site."""

    num_cookers = Cook.objects.count()
    num_dishes = Dish.objects.count()
    num_dish_types = DishType.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_cookers": num_cookers,
        "num_dishes": num_dishes,
        "num_dish_types": num_dish_types,
        "num_visits": num_visits + 1,
    }

    return render(request, "menu/index.html", context=context)


class DishListView(generic.ListView):
    model = Dish
    paginate_by = 7

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super(DishListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = DishSearchForm(initial={
            "name": name
        })

        return context

    def get_queryset(self) -> QuerySet:
        form = DishSearchForm(self.request.GET)
        if form.is_valid():
            return Dish.objects.select_related("dish_type").filter(
                name__icontains=form.cleaned_data["name"]
            )


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("menu:dish-list")


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("menu:dish-list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("menu:dish-list")


class DishTypeListView(generic.ListView):
    model = DishType
    paginate_by = 5
    context_object_name = "dish_type_list"
    template_name = "menu/dish_type_list.html"

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super(DishTypeListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = DishSearchForm(initial={
            "name": name
        })

        return context

    def get_queryset(self) -> QuerySet:
        form = DishTypeSearchForm(self.request.GET)
        if form.is_valid():
            return DishType.objects.filter(
                name__icontains=form.cleaned_data["name"]
            )


class DishTypeDetailView(LoginRequiredMixin, generic.DetailView):
    model = DishType
    template_name = "menu/dish_type_detail.html"
    queryset = DishType.objects.all().prefetch_related("dish_set__cookers")


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("menu:dish_type_list")
    template_name = "menu/dish_type_form.html"


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    fields = "__all__"
    template_name = "menu/dish_type_form.html"
    success_url = reverse_lazy("menu:dish_type_list")


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    success_url = reverse_lazy("menu:dish_type_list")
    template_name = "menu/dish_type_confirm_delete.html"


class CookListView(generic.ListView):
    model = Cook
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super(CookListView, self).get_context_data(**kwargs)

        username = self.request.GET.get("username", "")

        context["search_form"] = CookSearchForm(initial={
            "username": username
        })

        return context

    def get_queryset(self) -> QuerySet:
        form = CookSearchForm(self.request.GET)
        if form.is_valid():
            return Cook.objects.filter(
                username__icontains=form.cleaned_data["username"]
            )


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookCreationForm
    success_url = reverse_lazy("menu:cook-list")


class CookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookUpdateYearsForm
    success_url = reverse_lazy("menu:cook-list")


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("menu:cook-list")


@login_required
def toggle_assign_to_dish(request, pk) -> HttpResponse:
    cook = Cook.objects.get(id=request.user.id)
    if (
        Dish.objects.get(id=pk) in cook.dishes.all()
    ):
        cook.dishes.remove(pk)
    else:
        cook.dishes.add(pk)
    return HttpResponseRedirect(reverse_lazy("menu:dish-detail", args=[pk]))


templates/menu/cook_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div  class="mx-auto p-7" style="width:600px">
  <h1>Delete this Cook: {{ cook.username }}?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a class="btn btn-success" href="{% url 'menu:cook-detail' pk=cook.id %}">No!</a>
  </form>
</div>
{% endblock %}

templates/menu/cook_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="mx-auto p-7 w-50" style="width:600px">
  <h1>
    {{ cook.username }} | {{ cook.first_name }} {{ cook.last_name }}
    <a href="{% url 'menu:cook-delete' pk=cook.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'menu:cook-update' pk=cook.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>
  <strong><i><p>Years Of Experience: {{ cook.years_of_experience }}</p></i></strong>
  <hr>
  <ul>
      {% for dish in cook.dishes.all %}
        <li>{{ dish.name }}</li>
      {% endfor %}

  </ul>
  </div>
{% endblock %}

templates/menu/cook_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<div class="mx-auto p-7" style="width:600px">
  <h1>{{ object|yesno:"Update,Create" }} cook</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
</div>
{% endblock %}

templates/menu/cook_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="mx-auto p-7" style="width:600px">
  <h1>
     List of Cookers
  </h1>
  <h5>
    <a href="{% url 'menu:cook-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h5>
  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input class="btn-sm btn-light p-1" type="submit" value="🔎">
  </form>

  {% if cook_list %}
    <table class="table">
      <tr>
        <th>Username</th>
        <th>First Name</th>
        <th>Last Name</th>
      </tr>

      {% for cook in cook_list %}
        <tr>
          <td>
            <a href="{% url 'menu:cook-detail' pk=cook.id%}">{{ cook.username }}</a>
          </td>
          <td>
              {{ cook.first_name }}
          </td>
          <td>
              {{ cook.last_name }}
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no cooks available.</p>
  {% endif %}
    {% include "includes/pagination.html" %}

  </div>
{% endblock %}

templates/menu/dish_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div  class="mx-auto p-7" style="width:600px">
  <h1>Delete this Dish: {{ dish.name }}?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a class="btn btn-success" href="{% url 'menu:dish-detail' pk=dish.id %}">No!</a>
  </form>
</div>
{% endblock %}

templates/menu/dish_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="mx-auto p-7 w-50" style="width:600px">
  <h1>
    {{ dish.name }}
    <a href="{% url 'menu:dish-delete' pk=dish.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'menu:dish-update' pk=dish.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>
  ----------------------
  <strong><i><p>Traditional country food: {{ dish.dish_type }}</p></i></strong>
  ----------------------
  <h1>
  <h5><small>{{ dish.description }}</small></h5>
  --------------------------------------------------------------------------------
    <h3>Cookers
      {% if dish in user.dishes.all %}
      <a href="{% url 'menu:assign-to-dish' pk=dish.id %}" class="btn btn-danger link-to-page inline-related">
        Don't cook this dish
      </a>
    {% else %}
      <a href="{% url 'menu:assign-to-dish' pk=dish.id %}" class="btn btn-success link-to-page">
        Assign me to cook this dish
      </a>
    {% endif %}
    </h3>

  </h1>
  <hr>
  <ul>
    {% for cook in dish.cookers.all %}
      <li>{{ cook.username }} ({{ cook.first_name }} {{ cook.last_name }})</li>
    {% endfor %}
  </ul>
  </div>
{% endblock %}

templates/menu/dish_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<div class="mx-auto p-7" style="width:600px">
  <h1>{{ object|yesno:"Update,Create" }} dish</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
</div>
{% endblock %}

templates/menu/dish_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="mx-auto p-7" style="width:600px">
  <h1>
     Menu
  </h1>
  <h5>
    <a href="{% url 'menu:dish-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h5>
  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input class="btn-sm btn-light p-1" type="submit" value="🔎">
  </form>

  {% if dish_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Type</th>
      </tr>

      {% for dish in dish_list %}
        <tr>
          <td>
            <a href="{% url 'menu:dish-detail' pk=dish.id%}">{{ dish.name }}</a>
          </td>
          <td>
              {{ dish.price }}
          </td>
          <td>
              {{ dish.dish_type }}
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no dishes available.</p>
  {% endif %}
    {% include "includes/pagination.html" %}

  </div>

{% endblock %}

templates/menu/dish_type_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div  class="mx-auto p-7" style="width:600px">
  <h1>Delete this Country Type: {{ dishtype.name }}?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a class="btn btn-success" href="{% url 'menu:dish_type_detail' pk=dishtype.id %}">No!</a>
  </form>
</div>
{% endblock %}

templates/menu/dish_type_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="mx-auto p-7 w-50" style="width:600px">
  <h1 class="inline-related">
    {{ dishtype.name }}
    <a href="{% url 'menu:dish-type-delete' pk=dishtype.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'menu:dish-type-update' pk=dishtype.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>
  <hr>
  <ul>
    {% for dish in dishtype.dish_set.all %}
      <strong><p><li>{{ dish.name }}</li> </p> </strong>
      <i><p> {{ dish.description }} </p></i>
      <strong>Cookers:</strong>
      {% for cook in dish.cookers.all %}
        <p>{{ cook }}</p>

      {% endfor %}

    {% endfor %}
  </ul>
  </div>
{% endblock %}

templates/menu/dish_type_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<div class="mx-auto p-7" style="width:600px">
  <h1>{{ object|yesno:"Update,Create" }} dish country name</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
</div>
{% endblock %}

templates/menu/dish_type_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<div class="mx-auto p-7 w-50" style="width:600px">
  <h2>
    List of traditional cuisines
  </h2>
  <h5>
    <a href="{% url 'menu:dish-type-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h5>
  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
  <input class="btn-sm btn-light p-1" type="submit" value="🔎">
  </form>

  {% if dish_type_list %}
    <ul>
      {% for dish_type in dish_type_list %}
        <li>
          <a href="{% url 'menu:dish_type_detail' pk=dish_type.id %}">{{ dish_type.name }}</a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no dish types</p>
  {% endif %}
    {% include "includes/pagination.html" %}

</div>
{% endblock %}

templates/menu/index.html
{% extends "base.html" %}

{% block content %}
  <!DOCTYPE html>
<html lang="en" itemscope itemtype="http://schema.org/WebPage">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{{ ASSETS_ROOT }}/img/apple-icon.png">
  <link rel="icon" type="image/png" href="{{ ASSETS_ROOT }}/img/favicon.png">

  <title>
    The Restaurant
  </title>

  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
  <!-- Nucleo Icons -->
  <link href="{{ ASSETS_ROOT }}/css/nucleo-icons.css" rel="stylesheet" />
  <link href="{{ ASSETS_ROOT }}/css/nucleo-svg.css" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <!-- Material Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
  <!-- CSS Files -->
  <link id="pagestyle" href="{{ ASSETS_ROOT }}/css/material-kit.css?v=3.0.0" rel="stylesheet" />

</head>
<body class="presentation-page bg-gray-200">

  <header class="header-2">
    <div class="page-header min-vh-85 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/img.png')">
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white pt-3 mt-n5">Lizard Restaurant</h1>
            <p class="lead text-white mt-3">Welcome to The Best restaurant in the world <br /> Enjoy! </p>
          </div>
        </div>
      </div>
    </div>
  </header>
  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">
    <section class="pt-3 pb-4" id="count-stats">
      <div class="container">
        <div class="row">
          <div class="col-lg-9 mx-auto py-3">
            <div class="row">
              <div class="col-md-4 position-relative">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary"><span id="state1" countTo="{{ num_dishes }}">0</span>+</h1>
                  <h5 class="mt-3">Dishes</h5>
                  <p class="text-sm font-weight-normal">From best products, with love</p>
                </div>
                <hr class="vertical dark">
              </div>
              <div class="col-md-4 position-relative">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary"> <span id="state2" countTo="{{ num_dish_types }}">0</span>+</h1>
                  <h5 class="mt-3">Countries</h5>
                  <p class="text-sm font-weight-normal">We travelled a lot to get everything together</p>
                </div>
                <hr class="vertical dark">
              </div>
              <div class="col-md-4">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary" id="state3" countTo="{{ num_cookers }}">0</h1>
                  <h5 class="mt-3">Cookers</h5>
                  <p class="text-sm font-weight-normal">Most professional people get together to make tasty meals for u!</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

  <!--   Core JS Files   -->
  <script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>
  <!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
  <!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
  <!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
  <!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
  <!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>
  <!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
  <script src="{{ ASSETS_ROOT }}/js/material-kit.min.js?v=3.0.0" type="text/javascript"></script>
  <script type="text/javascript">
    if (document.getElementById('state1')) {
      const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
      if (!countUp.error) {
        countUp.start();
      } else {
        console.error(countUp.error);
      }
    }
    if (document.getElementById('state2')) {
      const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
      if (!countUp1.error) {
        countUp1.start();
      } else {
        console.error(countUp1.error);
      }
    }
    if (document.getElementById('state3')) {
      const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
      if (!countUp2.error) {
        countUp2.start();
      } else {
        console.error(countUp2.error);
      };
    }
  </script>
    </div>
</body>

</html>

{% endblock %}